### ISSUE TITLE
whitespace is added to target buffer

### ISSUE THREAD

**Issue by fommil** [ancane/popup-imenu#5]
I just realised that `popup-imenu` is causing this, but when I run the command on my emacs config file https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el

Whitespace is added just above where the popup appears. You can see it in the animated gif I created (trailing whitespace is highlighted in bright red)

![popup-imenu](https://cloud.githubusercontent.com/assets/1914041/12019024/0779eac4-ad63-11e5-8b5a-0bd323d4e111.gif)

**Comment by fommil** [comment]
btw, you can see it yourself by enabling the trailing whitespace

``` elisp
(add-hook 'prog-mode-hook
          (lambda() (setq show-trailing-whitespace t)))
```

**Comment by ancane** [comment]
This happens when `popup-imenu-position` is set to `center` or `fill-column`. Also it makes buffer modified.

**Comment by ancane** [comment]
The problem here is that it's only possible to place popup in desired column when the line is long enough. If there is no valid char at that position - row is filled with whitespaces.
I'll make popup-imenu to open at (point) by default and add some options to manage position for other positioning settings.
